MovemberBundle\Entity\Movember:
    type: entity
    table: null
    repositoryClass: MovemberBundle\Repository\MovemberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        codepost:
            type: string
            length: 255
        ville:
            type: string
            length: 255
        lati:
            type: string
            length: 255
        longt:
            type: string
            length: 255

    lifecycleCallbacks: {  }
