<?php

namespace MovemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * formulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formulaireRepository extends EntityRepository
{
}
