<?php

namespace MovemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovemberRepository extends EntityRepository
{
}
